### ISSUE TITLE
Cloudflare/Wrangler/workerd: add node_compat_v2 

### ISSUE THREAD

**Issue by shmuli9** [flarelabs-net/workers-nodejs-compat-matrix#13]

**Comment by vicb** [comment]
I guess you mean `nodejs_compat_v2` - `node_compat` is different and deprecated.

`nodejs_compat_v2` is now `nodejs_compat` only - that is after the 2024-09-23 compatibility date `nodejs_compat` implies `nodejs_compat_v2`.

It's a bit confusing but what you should remember is that js compatibility should be enabled with `nodejs_compat` and the date >= 2024-09-23 (`nodejs_compat_v2` still works whatever the date but is no more the recommended way)

And this is the last column:

<img width="210" alt="image" src="https://github.com/user-attachments/assets/00ed0c8b-b87d-4b15-a975-c2ec26cdca0c">
